apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aks-demo-app.fullname" . }}-config
  labels:
    {{- include "aks-demo-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
