{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aks-demo-app.fullname" . }}-secret
  labels:
    {{- include "aks-demo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEMO_API_KEY: {{ .Values.secret.DEMO_API_KEY | quote }}
{{- end }}